### ISSUE TITLE
Any idea why this URL won't work?

### ISSUE THREAD

**Issue by Justinzobel** [leoncowle/rss2masto#1]
https://pointieststick.com/feed

It's valid xml but it's sent as a file I guess by WordPress.

**Comment by leoncowle** [comment]
Add a trailing "/" to your feed url, i.e. "https://pointieststick.com/feed/". Without the trailing "/", the site is returning a 301-redirect response to https://pointieststick.com/feed/

**Comment by leoncowle** [comment]
Please do a git pull, and try again (using the one without the trailing "/"). I've now added basic support to handle 301/302 responses (it'll try the redirected-to url instead).

**Comment by Justinzobel** [comment]
Working now with the / I think the redirect still had some issues. But adding the / solved it.
